version: '3.8'

services:
  svc:
    build: .
    ports:
      - "{{port}}:{{port}}"
{% if static_support %}
      - "{{static_assets_port}}:{{static_assets_port}}"
{% endif %}
{% if db_support %}
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
{% endif %}
